---
tags: [JavaScript, spring-boot, groovy, cli, jquery, webjars]
projects: [spring-boot]
---
:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-spring-boot-cli-and-js

This is a basic app built with Spring Boot, Thymeleaf and Jquery. It has 3 main endpoints:

* / - show the index of the app instance and uptime from the app instance that served the request, which should change when loadbalanced and refreshed with multiple instances of the app running.
* /env - show the environment variables set for the application
* /exit - exit the application instance that served the request

== What you'll need

:java_version: 1.8
include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/prereq_editor_jdk_buildtools.adoc[]


:initial: /
:complete: /
include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/how_to_complete_this_guide.adoc[]

[[scratch]]
== Install Spring Boot's CLI
Spring Boot comes with a Command Line Interface. There are several ways to install it.

You can install it via gvm:

----
curl -s get.gvmtool.net | bash
----

With gvm installed, you then install the CLI:

----
gvm install springboot
spring --version
----

If you are using a Mac, you can also the CLI using Homebrew.

----
brew tap pivotal/tap
brew install springboot
spring --version
----

With either of these options, you are now in business to create a Spring application with minimal effort.

[[initial]]
== Creating a Spring application
Now create the simplest application possible.

`app.groovy`
[source,groovy]
----
include::app.groovy[lines=2..999]
----

This Spring MVC controller defines the REST endpoints

== Javascript library

This app uses jQuery. See the Groovy @Grab annotation to the top of your application that automatically fetches it.

[source,groovy]
----
include::app.groovy[lines=1]
----

NOTE: Feel free to read more about http://spring.io/blog/2014/01/03/utilizing-webjars-in-spring-boot[Spring Boot + webjars].

== The web templates

Thymeleaf templates are in the templates directory.

NOTE: Because we used webjars, jQuery is found at `webjars/jquery/<version>/<library>`.

== Running the application

Now launch the application.

----
spring run -cp . app.groovy
----

See the animation by visiting http://localhost:8080/.

----
cf push spring-boot-cf-demo app.groovy
----

See the animation by visiting http://spring-boot-cf-demo.systemdomain. Not that URL may not be available so you may need to use something like the `--random-route` option on the cf push command.

- Several paths are autoloaded for serving assets(see https://spring.io/blog/2014/01/03/utilizing-webjars-in-spring-boot[webjars] and https://spring.io/blog/2013/12/19/serving-static-web-content-with-spring-boot[static web content] blog entries for more details). That's why we placed our web template in the `/templates` folder.

From here you can add RESTful endpoints to the backend, work on your front end, and grow your application as needed.
