:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-spring-boot-cli-and-js

This guide shows how to use Spring Boot's Command Line Interface to create a rich application with a
backend support by Spring MVC and a web-based front end using Thymeleaf template engine and jQuery.

== What you'll build

You'll build a web application using Groovy and Spring while also using Thymeleaf and jQuery.

== What you'll need

include::https://raw.github.com/spring-guides/getting-started-macros/master/prereq_editor_jdk_buildtools.adoc[]


include::https://raw.github.com/spring-guides/getting-started-macros/master/how_to_complete_this_guide.adoc[]

[[scratch]]
== Install Spring Boot's CLI
Spring Boot comes with a Command Line Interface. You can either install it via gvm:

----
curl -s get.gvmtool.net | bash
----

With gvm installed, you then install the CLI:

----
gvm install springboot
spring --version
----

If you are using a Mac, you can also the CLI using Homebrew.

----
brew tap pivotal/tap
brew install springboot
spring --version
----

With either of these options, you are now in business to create a Spring application with minimal effort.

== Creating a Spring application
Now create the simplest application possible.

`app.groovy`
[source,groovy]
----
@Grab("thymeleaf-spring3")

import org.springframework.ui.Model

@Controller
class Application { 
	@RequestMapping("/greeting")
	public String greeting(@RequestParam(value="name", required=false, defaultValue="World") String name, Model model) {
		model.addAttribute("name", name);
		return "greeting";
	}
}
----

This Spring MVC controller defines a REST endpoint at `/greeting`. We'll write the template for that later in this guide.

== Adding a Javascript library

Let's demonstrate this using a jQuery animation. We first need to grab a copy of jQuery. The simplest option would to add a Groovy @Grab annotation to our application that automatically fetches it.

Update your application so it looks like this:

[source,groovy]
----
@Grab("org.webjars:jquery:2.0.3-1") // this will automatically fetch jquery
@Grab("thymeleaf-spring3")

import org.springframework.ui.Model

@Controller
class Application { 
	@RequestMapping("/greeting")
	public String greeting(@RequestParam(value="name", required=false, defaultValue="World") String name, Model model) {
		model.addAttribute("name", name);
		return "greeting";
	}
}
----

NOTE: Feel free to read more about http://spring.io/blog/2014/01/03/utilizing-webjars-in-spring-boot[Spring Boot + webjars].

== Writing a web front end

Let's create a Thymeleaf template to support our RESTful endpoint.

----
mkdir templates
----

Now add the following template:

`templates/greeting.html`
[source,html]
----
<!DOCTYPE HTML>
<html xmlns:th="http://www.thymeleaf.org">
<head>
    <title>Getting Started: Spring Boot CLI + Javascript</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <script src="webjars/jquery/2.0.3/jquery.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $('p').animate({
                fontSize: '48px'
            }, "slow");
        });
    </script>
</head>
<body>
    <p th:text="'Hello, ' + ${name} + '!'" />
</body>
</html>
----

NOTE: Because we used webjars, jQuery is found at `webjars/jquery/<version>/<library>`.

== Running the application

Now launch the application.

----
spring run -cp . app.groovy
----

See the animation by visiting http://localhost:8080.

This almost empty application comes preloaded with a lot of features thanks to Spring Boot.

- @Controller gives a signal that this is a Spring MVC application and Boot will launch an embedded
Tomcat servlet container.
- Several paths are autoloaded for serving assets(see https://spring.io/blog/2014/01/03/utilizing-webjars-in-spring-boot[webjars] and https://spring.io/blog/2013/12/19/serving-static-web-content-with-spring-boot[static web content] blog entries for more details). That's why we placed our web template in the `/templates` folder.

From here you can add RESTful endpoints to the backend, work on your front end, and grow your application as needed.

== Summary
Spring Boot CLI provides a rapid way to create a back end server app. It also supports plugging in your 
favorite Javascript resources and HTML templates. You also could have staged CSS assets. Bottom line: you don't have to create a project file. Instead, you can dive quickly into building your application.


