:spring_version: 4.0.0.RC1
:spring_boot_version: 0.5.0.M6
:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-spring-boot-cli-and-js

This guide shows how to use Spring Boot's Command Line Interface to create a rich application with a
backend support by Spring MVC and a web-based front end using Thymeleaf template engine and jQuery.

== What you'll build

You'll build a web application using Groovy and Spring while also using Thymeleaf and jQuery.

== What you'll need

include::https://raw.github.com/spring-guides/getting-started-macros/master/prereq_editor_jdk_buildtools.adoc[]


include::https://raw.github.com/spring-guides/getting-started-macros/master/how_to_complete_this_guide.adoc[]

[[scratch]]
== Install Spring Boot's CLI
Spring Boot comes with a Command Line Interface. You can either install it via gvm:

----
curl -s get.gvmtool.net | bash
----

With gvm installed, you then install the CLI:

----
gvm install springboot
spring --version
----

If you are using a Mac, you can also the CLI using Homebrew.

----
brew tap pivotal/tap
brew install springboot
spring --version
----

With either of these options, you are now in business to create a Spring application with minimal effort.

== Creating a Spring application
Now create the simplest application possible.

`app.groovy`
[source,groovy]
----
@Controller
class Application { }
----

NOTE: You read that right. This is an empty class with an @Controller annotation.

We need a place to host our client-side assets.

----
mkdir -p public
cd public
wget http://code.jquery.com/jquery-2.0.3.js
cd ..
----

We just downloaded http://jquery.com/download/[jQuery].

Let's create a simple web page that has a nice animation.

`public/index.html`
[source,html]
----
<!DOCTYPE HTML>
<html xmlns:th="http://www.thymeleaf.org">
<head>
    <title>Getting Started: Spring Boot CLI + Javascript</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <script src="jquery-2.0.3.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $('p').animate({
                fontSize: '48px'
            }, "slow");
        });
    </script>
</head>
<body>
    <p>Greetings Spring Boot user!</p>
</body>
</html>
----

Now launch the application.

----
spring run -cp . app.groovy
----

See the animation by visiting http://localhost:8080.

This seemingly empty application comes preloaded with a lot of features thanks to Spring Boot.
@Controller gives a signal that this is a Spring MVC application and Boot will launch an embedded
Tomcat servlet container.


